### ISSUE TITLE
Api doesnt working

### ISSUE THREAD

**Issue by prescientmoon** [neelpatel05/periodic-table-api#1]
I tried to fetch some data from a js script, but it gives me an error. Is it still hosted?

**Comment by prescientmoon** [comment]
I just realised how dumb i am. Api isnt* working is the corect form ....

**Comment by neelpatel05** [comment]
> I tried to fetch some data from a js script, but it gives me an error. Is it still hosted?

It is fixed and running on the [https://neelpatel05.pythonanywhere.com](https://neelpatel05.pythonanywhere.com/)

**Comment by prescientmoon** [comment]
Thanks
