### ISSUE TITLE
Problem Fetching certain data

### ISSUE THREAD

**Issue by ghost** [neelpatel05/periodic-table-api#3]
I have a little problem when getting the data. Is it vanDerWaalsRadius or vanDelWaalsRadius ?
In you README.md, I see a "vanDerWaalsRadius". And the name is, if I rember well, vanDerWaals. But, when getting the data, i have a vanDelWaals in the dict i get for any element :/
Please answer me or modify the file if it's wrong.

**Comment by neelpatel05** [comment]
There is a typo. It is "vanDelWaalsRadius" and not "vanDerWaalsRadius". As this service is used by many of the users. By changing it to "vanDerWaalsRadius" will create a disruption in their application. You can use "vanDelWaalsRadius" to fetch from the data you receive :)

**Comment by ghost** [comment]
Thanks, got it !
