### ISSUE TITLE
404 Response

### ISSUE THREAD

**Issue by Jonah987654321** [neelpatel05/periodic-table-api#5]
I am getting a 404 response when I am making a request to the API.
I use this link: [https://neelpatel05.pythonanywhere.com/element/symbol?symbol=Iron](https://neelpatel05.pythonanywhere.com/element/symbol?symbol=Iron) to fetch the data

**Comment by neelpatel05** [comment]
The link you are using is incorrect. You are using the atomic name 'Iron' in the 'symbol' endpoint. Use either of the following

Atomic Name: `https://neelpatel05.pythonanywhere.com/element/atomicname?atomicname=Iron`
Atomic Symbol: `https://neelpatel05.pythonanywhere.com/element/symbol?symbol=Fe`

**Comment by Jonah987654321** [comment]
Sorry, my mistake
