### ISSUE TITLE
Is this API still active ?

### ISSUE THREAD

**Issue by hanif-page** [neelpatel05/periodic-table-api#6]
Hi, I just wanna clarify. **Is this API still active normally ?** Because when I access the API link, it says on the website coming soon (from the pythonanywhere).

note : I want to use this API for my project. First time I checked it, it works normally. But then after a few times, the link is like didn't active until right now.

**Comment by neelpatel05** [comment]
Hey, The link is working now, and apologize for late resolving the error. I am using the free package of "pythonanywhere". I have to relaunch the app every 3 months. I had forgotten to do this time. Will keep in mind ahead to renew within the time frame. Thanks for reaching out to me. Cheers!

**Comment by hanif-page** [comment]
Wow okay, thanks for your attention and response. Cheers!

note : Sorry if I'm too late to reply to this comment, I didn't check my GitHub for a while
