### ISSUE TITLE
The website stopped working.

### ISSUE THREAD

**Issue by Rishit-9** [neelpatel05/periodic-table-api#8]
You should switch to [Netlify](https://www.netlify.com/). It's really good and widely used.
![image](https://user-images.githubusercontent.com/83908451/206496911-211fd4fc-4aae-45b7-916a-dde5cc59499d.png)

**Comment by Rishit-9** [comment]
@neelpatel05 please fix it

**Comment by neelpatel05** [comment]
@Rishit-Gupta-RG I have resolved the issue. It's up and running. Apologies for the delay and thanks for waiting!
